ALTER TABLE tenants ADD COLUMN latitude DECIMAL(10,7);
ALTER TABLE tenants ADD COLUMN longitude DECIMAL(10,7);
ALTER TABLE tenants ADD COLUMN phone VARCHAR(20);
ALTER TABLE tenants ADD COLUMN address VARCHAR(500);
