import { Link, Navigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { FiCompass, FiStar, FiShield, FiZap, FiArrowRight, FiMapPin, FiDollarSign, FiCalendar } from 'react-icons/fi'
import { useAuth } from '../context/AuthContext'
import { useTenant } from '../context/TenantProvider'
import LoadingSpinner from '../components/LoadingSpinner'

const fadeUp = {
  initial: { opacity: 0, y: 30 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: '-100px' },
  transition: { duration: 0.6 },
}

const features = [
  { icon: FiZap, title: 'AI-Powered Itineraries', desc: 'Smart travel plans generated by advanced AI tailored to your preferences.' },
  { icon: FiMapPin, title: 'Smart Destination Planning', desc: 'Discover optimal routes, hidden gems, and local favorites.' },
  { icon: FiDollarSign, title: 'Budget Optimization', desc: 'Get the best value with intelligent budget allocation across your trip.' },
  { icon: FiShield, title: 'Real-Time Updates', desc: 'Stay informed with instant notifications about your travel plans.' },
]

const destinations = [
  { name: 'Goa', desc: 'Beaches & Nightlife', color: 'from-cyan-500 to-blue-600' },
  { name: 'Manali', desc: 'Mountains & Adventure', color: 'from-emerald-500 to-teal-600' },
  { name: 'Jaipur', desc: 'Heritage & Culture', color: 'from-orange-500 to-red-600' },
  { name: 'Kerala', desc: 'Backwaters & Nature', color: 'from-green-500 to-emerald-600' },
  { name: 'Ladakh', desc: 'Land of High Passes', color: 'from-purple-500 to-indigo-600' },
  { name: 'Udaipur', desc: 'City of Lakes', color: 'from-pink-500 to-rose-600' },
]

export default function LandingPage() {
  const { isAuthenticated, loading } = useAuth()
  const tenant = useTenant()
  const agencyName = tenant.branding?.agencyName || 'TravelPlanner'
  const tagline = tenant.branding?.tagline || ''
  const logoUrl = tenant.branding?.logoUrl
  const backgroundImage = tenant.branding?.backgroundImage
  const overlayOpacity = tenant.branding?.overlayOpacity ?? 70
  const overlayBlur = tenant.branding?.overlayBlur || 'sm'
  const templateStyle = tenant.branding?.templateStyle || 'modern'

  if (loading) return <LoadingSpinner fullScreen />
  if (isAuthenticated) {
    return <Navigate to="/dashboard" replace />
  }

  return (
    <div className="min-h-screen overflow-hidden relative bg-surface">
      {backgroundImage && (
        <div className="fixed inset-0 pointer-events-none">
          <img src={backgroundImage} alt="" className="w-full h-full object-cover" />
          <div
            className="absolute inset-0"
            style={{
              backgroundColor: `rgba(0,0,0,${overlayOpacity / 100})`,
              backdropFilter: overlayBlur === 'none' ? 'none' : `blur(${{ sm: '4px', md: '12px', lg: '24px' }[overlayBlur] || '4px'})`,
            }}
          />
        </div>
      )}
      {!backgroundImage && (
        <>
          {/* Animated Background */}
          <div className="fixed inset-0 pointer-events-none">
            <div className="absolute top-[-20%] left-[-10%] w-[40%] h-[40%] bg-primary-500/10 rounded-full blur-[120px]" />
            <div className="absolute bottom-[-10%] right-[-10%] w-[35%] h-[35%] bg-accent-500/10 rounded-full blur-[120px]" />
            <div className="absolute top-[40%] right-[20%] w-[25%] h-[25%] bg-emerald-500/8 rounded-full blur-[100px]" />
            {[...Array(20)].map((_, i) => (
              <motion.div
                key={i}
                className="absolute w-1 h-1 bg-white/10 rounded-full"
                style={{
                  left: `${Math.random() * 100}%`,
                  top: `${Math.random() * 100}%`,
                }}
                animate={{
                  y: [0, -30, 0],
                  opacity: [0.2, 0.5, 0.2],
                }}
                transition={{
                  duration: 3 + Math.random() * 4,
                  repeat: Infinity,
                  delay: Math.random() * 5,
                }}
              />
            ))}
          </div>

          {/* Floating Orbs */}
          <div className="fixed inset-0 pointer-events-none overflow-hidden">
            <div className="absolute top-1/4 left-1/6 w-72 h-72 bg-primary-500/10 rounded-full blur-[120px] animate-pulse-soft" />
            <div className="absolute bottom-1/3 right-1/6 w-96 h-96 bg-accent-500/8 rounded-full blur-[120px] animate-pulse-soft" style={{ animationDelay: '1s' }} />
            <div className="absolute top-2/3 left-1/3 w-48 h-48 bg-emerald-500/6 rounded-full blur-[100px] animate-pulse-soft" style={{ animationDelay: '2s' }} />
          </div>
        </>
      )}

      {/* Nav */}
      <nav className="relative z-10 flex items-center justify-between px-6 py-5 max-w-7xl mx-auto">
        <Link to="/" className="flex items-center gap-2">
          {logoUrl ? (
            <img src={logoUrl} alt={agencyName} className="h-10 w-auto" />
          ) : (
            <div className="w-10 h-10 bg-gradient-to-br from-primary-500 to-accent-500 rounded-xl flex items-center justify-center">
              <FiCompass className="w-5 h-5 text-white" />
            </div>
          )}
          <span className="text-xl font-bold gradient-text">{agencyName}</span>
        </Link>
        <div className="flex items-center gap-4">
          <Link to="/login" className="btn-secondary">Sign In</Link>
          <Link to="/register" className="btn-primary">Get Started</Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative z-10 max-w-7xl mx-auto px-6 pt-20 pb-32">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          <motion.div initial={{ opacity: 0, x: -30 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.8 }}>
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="inline-flex items-center gap-2 px-4 py-1.5 glass rounded-full text-sm text-primary-300 mb-6 border-primary-500/20 animate-glow"
            >
              <FiStar className="w-4 h-4 text-accent-400" />
              AI-Powered Travel Planning
            </motion.div>
            <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold text-white leading-tight mb-6 text-shadow">
              Plan Your
              <span className="gradient-text-glow block">Dream Trip</span>
              with AI
            </h1>
            {tagline && (
              <motion.p
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
                className="text-lg text-primary-300 mb-2 font-medium"
              >
                {tagline}
              </motion.p>
            )}
            <p className="text-lg text-gray-400 mb-8 max-w-lg leading-relaxed">
              Let artificial intelligence craft the perfect itinerary for your next adventure. 
              Smart budgets, personalized recommendations, and seamless planning — all in one place.
            </p>
            <div className="flex items-center gap-4">
              <Link to="/register" className="btn-primary text-lg px-8 py-4 flex items-center gap-2 group">
                Start Planning Free <FiArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </Link>
              <Link to="/login" className="btn-secondary text-lg px-8 py-4">
                Sign In
              </Link>
            </div>
              {/* Mood Search */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.4 }}
                className="mt-8 pt-8 border-t border-surface-border/50"
              >
                <p className="text-sm text-gray-400 mb-3">How are you feeling? Let AI match the perfect trip.</p>
                <div className="flex flex-wrap gap-2">
                  {['Romantic', 'Adventurous', 'Relaxed', 'Cultural', 'Budget', 'Luxury'].map((mood) => (
                    <Link
                      key={mood}
                      to="/register"
                      className="px-4 py-1.5 text-sm rounded-full glass border border-primary-500/20 text-gray-300 hover:border-primary-500/50 hover:text-white hover:bg-primary-500/5 hover:-translate-y-0.5 transition-all duration-200"
                    >
                      {mood}
                    </Link>
                  ))}
                </div>
              </motion.div>
              <div className="flex items-center gap-8 mt-8 pt-8 border-t border-surface-border">
                <div>
                  <p className="text-2xl font-bold text-white">10K+</p>
                  <p className="text-sm text-gray-400">Trips Planned</p>
                </div>
                <div>
                  <p className="text-2xl font-bold text-white">4.9</p>
                  <p className="text-sm text-gray-400">User Rating</p>
                </div>
                <div>
                  <p className="text-2xl font-bold text-white">50+</p>
                  <p className="text-sm text-gray-400">Destinations</p>
                </div>
              </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="relative hidden lg:block"
          >
            <div className="relative">
              <div className="absolute -inset-4 bg-gradient-to-r from-primary-500/20 to-accent-500/20 rounded-[2rem] blur-3xl opacity-50 animate-glow-lg" />
              <motion.div
                animate={{ y: [0, -15, 0] }}
                transition={{ duration: 5, repeat: Infinity, ease: 'easeInOut' }}
                className="glass-strong rounded-3xl p-8 border border-primary-500/20 relative"
              >
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-3 h-3 bg-red-500 rounded-full" />
                  <div className="w-3 h-3 bg-yellow-500 rounded-full" />
                  <div className="w-3 h-3 bg-green-500 rounded-full" />
                </div>
                <div className="space-y-4">
                  <motion.div
                    whileHover={{ x: 5 }}
                    className="flex items-center gap-4 p-4 bg-surface-lighter/80 rounded-xl hover:bg-surface-lighter transition-colors cursor-default"
                  >
                    <div className="w-12 h-12 bg-gradient-to-br from-primary-500/20 to-accent-500/20 rounded-xl flex items-center justify-center">
                      <FiMapPin className="w-6 h-6 text-primary-400" />
                    </div>
                    <div>
                      <p className="text-sm text-gray-400">Destination</p>
                      <p className="text-white font-semibold">Goa, India</p>
                    </div>
                  </motion.div>
                  <motion.div
                    whileHover={{ x: 5 }}
                    className="flex items-center gap-4 p-4 bg-surface-lighter/80 rounded-xl hover:bg-surface-lighter transition-colors cursor-default"
                  >
                    <div className="w-12 h-12 bg-gradient-to-br from-emerald-500/20 to-teal-500/20 rounded-xl flex items-center justify-center">
                      <FiCalendar className="w-6 h-6 text-emerald-400" />
                    </div>
                    <div>
                      <p className="text-sm text-gray-400">Duration</p>
                      <p className="text-white font-semibold">4 Days</p>
                    </div>
                  </motion.div>
                  <motion.div
                    whileHover={{ x: 5 }}
                    className="flex items-center gap-4 p-4 bg-surface-lighter/80 rounded-xl hover:bg-surface-lighter transition-colors cursor-default"
                  >
                    <div className="w-12 h-12 bg-gradient-to-br from-accent-500/20 to-orange-500/20 rounded-xl flex items-center justify-center">
                      <FiDollarSign className="w-6 h-6 text-accent-400" />
                    </div>
                    <div>
                      <p className="text-sm text-gray-400">Budget</p>
                      <p className="text-white font-semibold">₹25,000</p>
                    </div>
                  </motion.div>
                </div>
              </motion.div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section className="relative z-10 max-w-7xl mx-auto px-6 py-24">
        <motion.div className="text-center mb-16" {...fadeUp}>
          <h2 className="text-4xl font-bold text-white mb-4">
            Everything You Need to
            <span className="gradient-text"> Plan Perfectly</span>
          </h2>
          <p className="text-gray-400 max-w-2xl mx-auto">
            From smart itineraries to budget optimization, we've got your entire trip covered.
          </p>
        </motion.div>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feat, i) => (
            <motion.div
              key={feat.title}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className="card card-hover group card-lift"
            >
              <div className="w-14 h-14 bg-gradient-to-br from-primary-500/20 to-accent-500/20 rounded-2xl flex items-center justify-center mb-4 group-hover:scale-110 group-hover:from-primary-500/30 group-hover:to-accent-500/30 transition-all duration-300">
                <feat.icon className="w-7 h-7 text-primary-400 group-hover:text-primary-300 transition-colors" />
              </div>
              <h3 className="text-lg font-semibold text-white mb-2 group-hover:text-transparent group-hover:bg-clip-text group-hover:bg-gradient-to-r group-hover:from-primary-400 group-hover:to-accent-400 transition-all duration-300">{feat.title}</h3>
              <p className="text-sm text-gray-400 group-hover:text-gray-300 transition-colors">{feat.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Destinations */}
      <section className="relative z-10 max-w-7xl mx-auto px-6 py-24">
        <motion.div className="text-center mb-16" {...fadeUp}>
          <h2 className="text-4xl font-bold text-white mb-4">
            Popular <span className="gradient-text">Destinations</span>
          </h2>
          <p className="text-gray-400">Explore trending destinations planned by our community.</p>
        </motion.div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {destinations.map((dest, i) => (
            <Link
              key={dest.name}
              to="/register"
              className="block"
            >
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                whileHover={{ y: -8, scale: 1.02 }}
                className="card overflow-hidden group cursor-pointer card-lift border-primary-500/0 hover:border-primary-500/30"
              >
                <div className={`h-36 -mx-6 -mt-6 mb-4 bg-gradient-to-br ${dest.color} opacity-80 group-hover:opacity-100 transition-all duration-500 group-hover:scale-110`} />
                <h3 className="text-xl font-semibold text-white group-hover:gradient-text transition-all duration-300">{dest.name}</h3>
                <p className="text-sm text-gray-400 group-hover:text-gray-300 transition-colors">{dest.desc}</p>
              </motion.div>
            </Link>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="relative z-10 max-w-7xl mx-auto px-6 py-24">
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          className="relative"
        >
          <div className="absolute -inset-10 bg-gradient-to-r from-primary-500/10 to-accent-500/10 rounded-[3rem] blur-3xl" />
          <div className="relative glass-strong rounded-3xl p-12 md:p-20 text-center border-primary-500/20 overflow-hidden">
            <div className="absolute top-0 right-0 w-64 h-64 bg-primary-500/10 rounded-full blur-[80px] -translate-y-1/2 translate-x-1/2" />
            <div className="absolute bottom-0 left-0 w-64 h-64 bg-accent-500/10 rounded-full blur-[80px] translate-y-1/2 -translate-x-1/2" />
            <div className="relative">
              <h2 className="text-4xl md:text-5xl font-bold text-white mb-6 text-shadow">
                Ready to Plan Your<br />
                <span className="gradient-text-glow">Next Adventure?</span>
              </h2>
              <p className="text-gray-400 mb-8 max-w-lg mx-auto text-lg">
                Join thousands of travelers who use AI to create unforgettable experiences.
              </p>
              <Link to="/register" className="btn-primary text-lg px-10 py-4 inline-flex items-center gap-2 group">
                Get Started Free <FiArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </Link>
            </div>
          </div>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="relative z-10 border-t border-surface-border py-8">
        <div className="max-w-7xl mx-auto px-6 flex items-center justify-between">
          <div className="flex items-center gap-2">
            {logoUrl ? (
              <img src={logoUrl} alt={agencyName} className="h-6 w-auto" />
            ) : (
              <FiCompass className="w-5 h-5 text-primary-400" />
            )}
            <span className="text-sm text-gray-400">{agencyName}</span>
          </div>
          <p className="text-sm text-gray-500">© 2026 {agencyName}. AI-Powered Travel.</p>
        </div>
      </footer>
    </div>
  )
}
